### ISSUE TITLE
Support for DateOnly and TimeOnly and maybe other new types

### ISSUE THREAD

**Issue by inf9144** [6bee/aqua-core#46]
Hey,
could we get support for DateOnly and TimeOnly (and maybe if somebody is on it - new framework types like Int128?) :-)

I think it's missing in JsonConverterHelper._typeReaders.
Searching and comparing with the implementation for DateTime we found more occurences with specialised implementations like in the KnownTypesRegistry and in DynamicObjectMapper ;-)

Thanks in advance!

Best regards,
Alex

**Comment by inf9144** [comment]
Branched - will create a pull request for this :-)

**Comment by inf9144** [comment]
https://github.com/6bee/aqua-core/pull/47

**Comment by 6bee** [comment]
Hi Alexander - thanks a lot for your contribution. It is highly appreciated.

**Comment by 6bee** [comment]
@inf9144 
FYI: I had to revert to protobuf-net v2 since remote linq cannot work with v3. See [here](https://github.com/6bee/aqua-core/blob/main/src/Aqua.protobuf-net/Aqua.protobuf-net.csproj#L15) for more info.
What's more, I've also removed .net 9.0 targets for library projects since there are no dependencies specific to this version.
